<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework> 
    <ImplicitUsings>enable</ImplicitUsings> 
    <Nullable>enable</Nullable>
    <PublishSingleFile>true</PublishSingleFile> 
    <SelfContained>false</SelfContained> 
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <Target Name="CopyNkxPlugin" AfterTargets="Publish"> 
    <Copy SourceFiles="$(ProjectDir)inNKX.wcx64" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
